import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { NavBar } from "@/components/navbar";
import { CustomizeDialog } from "@/components/dialog/customize-dialog";
import { DialogProvider } from "@/providers/dialog-provider";
import { Toaster } from "@/components/ui/toaster";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="h-full px-5 sm:px-16 md:px-36 lg:px-36">
          <NavBar />
          <DialogProvider />
          <Toaster />
          {children}
        </div>
      </body>
    </html>
  );
}
